In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/emirhanakku/e-commerce-order-risk-classification-dataset/synthetic_ecommerce_order_risk_dataset.csv

In [2]:
import numpy as np 
import pandas as pd
import os

df=pd.read_csv("/kaggle/input/datasets/emirhanakku/e-commerce-order-risk-classification-dataset/synthetic_ecommerce_order_risk_dataset.csv")
df.head(1)

,order_id,order_date,country,device_type,traffic_source,payment_method,product_category,customer_age_days,previous_orders,avg_order_value_eur,...,shipping_distance_km,delivery_days_estimated,late_delivery_risk,address_mismatch,high_risk_ip,customer_support_contacts,review_score,is_returned,is_fraud,risk_label
0,ORD-2024-001936,2024-01-03,Belgium,Mobile,Paid Ads,Credit Card,Sports,381,3,28.66,...,105.7,5,0,0,0,0,4.4,0,0,Normal

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   order_id                   12000 non-null  object
 1   order_date                 12000 non-null  object
 2   country                    12000 non-null  object
 3   device_type                12000 non-null  object
 4   traffic_source             12000 non-null  object
 5   payment_method             12000 non-null  object
 6   product_category           12000 non-null  object
 7   customer_age_days          12000 non-null  int64
 8   previous_orders            12000 non-null  int64
 9   avg_order_value_eur        12000 non-null  float64
 10  order_value_eur            12000 non-null  float64
 11  quantity                   12000 non-null  int64
 12  discount_rate              12000 non-null  float64
 13  shipping_distance_km       12000 non-null  float64
 14  delivery_days_estimated    12000 non-null  int64
 15  late_delivery_risk         12000 non-null  int64
 16  address_mismatch           12000 non-null  int64
 17  high_risk_ip               12000 non-null  int64
 18  customer_support_contacts  12000 non-null  int64
 19  review_score               12000 non-null  float64
 20  is_returned                12000 non-null  int64
 21  is_fraud                   12000 non-null  int64
 22  risk_label                 12000 non-null  object
dtypes: float64(5), int64(10), object(8)
memory usage: 2.1+ MB

In [4]:
df.tail(1)

,order_id,order_date,country,device_type,traffic_source,payment_method,product_category,customer_age_days,previous_orders,avg_order_value_eur,...,shipping_distance_km,delivery_days_estimated,late_delivery_risk,address_mismatch,high_risk_ip,customer_support_contacts,review_score,is_returned,is_fraud,risk_label
11999,ORD-2024-007271,2024-05-23,Netherlands,Desktop,Organic Search,PayPal,Beauty,288,2,35.58,...,406.6,3,0,0,0,1,3.7,0,0,Normal

In [5]:
df.describe()

,customer_age_days,previous_orders,avg_order_value_eur,order_value_eur,quantity,discount_rate,shipping_distance_km,delivery_days_estimated,late_delivery_risk,address_mismatch,high_risk_ip,customer_support_contacts,review_score,is_returned,is_fraud
count,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000
mean,352.789083,1.943417,48.940278,61.053339,2.171833,0.146857,479.196567,4.058917,0.060000,0.048583,0.044167,0.200667,4.412433,0.092667,0.037250
std,237.556088,1.902590,28.716864,55.540429,1.625534,0.113934,330.305205,1.105312,0.237497,0.215004,0.205474,0.478803,0.545286,0.289977,0.189382
min,5.000000,0.000000,8.000000,5.000000,1.000000,0.000000,5.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.300000,0.000000,0.000000
25%,177.000000,1.000000,29.070000,26.617500,1.000000,0.060000,236.100000,3.000000,0.000000,0.000000,0.000000,0.000000,4.100000,0.000000,0.000000
50%,299.000000,1.000000,42.100000,45.335000,2.000000,0.120000,404.450000,4.000000,0.000000,0.000000,0.000000,0.000000,4.500000,0.000000,0.000000
75%,475.000000,3.000000,61.010000,75.952500,3.000000,0.210000,645.225000,5.000000,0.000000,0.000000,0.000000,0.000000,4.900000,0.000000,0.000000
max,1832.000000,13.000000,350.450000,810.750000,8.000000,0.750000,2589.700000,9.000000,1.000000,1.000000,1.000000,5.000000,5.000000,1.000000,1.000000

In [6]:
df.isnull().sum()

order_id                     0
order_date                   0
country                      0
device_type                  0
traffic_source               0
payment_method               0
product_category             0
customer_age_days            0
previous_orders              0
avg_order_value_eur          0
order_value_eur              0
quantity                     0
discount_rate                0
shipping_distance_km         0
delivery_days_estimated      0
late_delivery_risk           0
address_mismatch             0
high_risk_ip                 0
customer_support_contacts    0
review_score                 0
is_returned                  0
is_fraud                     0
risk_label                   0
dtype: int64

In [7]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
11995    False
11996    False
11997    False
11998    False
11999    False
Length: 12000, dtype: bool

In [8]:
df.dropna()

,order_id,order_date,country,device_type,traffic_source,payment_method,product_category,customer_age_days,previous_orders,avg_order_value_eur,...,shipping_distance_km,delivery_days_estimated,late_delivery_risk,address_mismatch,high_risk_ip,customer_support_contacts,review_score,is_returned,is_fraud,risk_label
0,ORD-2024-001936,2024-01-03,Belgium,Mobile,Paid Ads,Credit Card,Sports,381,3,28.66,...,105.7,5,0,0,0,0,4.4,0,0,Normal
1,ORD-2025-006495,2025-11-26,Netherlands,Desktop,Email,Debit Card,Garden,561,6,41.93,...,528.2,4,0,0,0,0,4.8,0,0,Normal
2,ORD-2023-001721,2023-11-07,Netherlands,Mobile,Organic Search,Debit Card,Garden,324,2,102.67,...,175.1,5,0,0,0,0,3.3,0,0,Normal
3,ORD-2024-009121,2024-05-28,Netherlands,Mobile,Organic Search,Klarna,Electronics,378,3,72.71,...,271.4,3,0,0,0,0,4.2,1,0,Return Risk
4,ORD-2025-000361,2025-01-31,Netherlands,Desktop,Direct,Bank Transfer,Home & Kitchen,447,5,52.26,...,285.3,3,0,1,0,0,5.0,0,0,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,ORD-2023-011965,2023-02-19,France,Mobile,Social Media,Credit Card,Garden,742,3,25.75,...,121.4,3,0,0,0,1,4.5,0,0,Normal
11996,ORD-2023-005192,2023-05-12,France,Mobile,Organic Search,Debit Card,Fashion,152,1,96.29,...,225.5,4,0,0,0,0,5.0,0,0,Normal
11997,ORD-2024-005391,2024-06-13,Germany,Mobile,Organic Search,Credit Card,Fashion,130,0,114.14,...,669.6,5,0,0,0,0,4.5,0,0,Normal
11998,ORD-2025-000861,2025-04-04,Poland,Desktop,Marketplace,PayPal,Fashion,203,1,21.60,...,229.4,5,0,0,0,0,4.4,0,0,Normal
11999,ORD-2024-007271,2024-05-23,Netherlands,Desktop,Organic Search,PayPal,Beauty,288,2,35.58,...,406.6,3,0,0,0,1,3.7,0,0,Normal

In [9]:
df.fillna(0)

,order_id,order_date,country,device_type,traffic_source,payment_method,product_category,customer_age_days,previous_orders,avg_order_value_eur,...,shipping_distance_km,delivery_days_estimated,late_delivery_risk,address_mismatch,high_risk_ip,customer_support_contacts,review_score,is_returned,is_fraud,risk_label
0,ORD-2024-001936,2024-01-03,Belgium,Mobile,Paid Ads,Credit Card,Sports,381,3,28.66,...,105.7,5,0,0,0,0,4.4,0,0,Normal
1,ORD-2025-006495,2025-11-26,Netherlands,Desktop,Email,Debit Card,Garden,561,6,41.93,...,528.2,4,0,0,0,0,4.8,0,0,Normal
2,ORD-2023-001721,2023-11-07,Netherlands,Mobile,Organic Search,Debit Card,Garden,324,2,102.67,...,175.1,5,0,0,0,0,3.3,0,0,Normal
3,ORD-2024-009121,2024-05-28,Netherlands,Mobile,Organic Search,Klarna,Electronics,378,3,72.71,...,271.4,3,0,0,0,0,4.2,1,0,Return Risk
4,ORD-2025-000361,2025-01-31,Netherlands,Desktop,Direct,Bank Transfer,Home & Kitchen,447,5,52.26,...,285.3,3,0,1,0,0,5.0,0,0,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,ORD-2023-011965,2023-02-19,France,Mobile,Social Media,Credit Card,Garden,742,3,25.75,...,121.4,3,0,0,0,1,4.5,0,0,Normal
11996,ORD-2023-005192,2023-05-12,France,Mobile,Organic Search,Debit Card,Fashion,152,1,96.29,...,225.5,4,0,0,0,0,5.0,0,0,Normal
11997,ORD-2024-005391,2024-06-13,Germany,Mobile,Organic Search,Credit Card,Fashion,130,0,114.14,...,669.6,5,0,0,0,0,4.5,0,0,Normal
11998,ORD-2025-000861,2025-04-04,Poland,Desktop,Marketplace,PayPal,Fashion,203,1,21.60,...,229.4,5,0,0,0,0,4.4,0,0,Normal
11999,ORD-2024-007271,2024-05-23,Netherlands,Desktop,Organic Search,PayPal,Beauty,288,2,35.58,...,406.6,3,0,0,0,1,3.7,0,0,Normal

In [10]:
df.dropna()

,order_id,order_date,country,device_type,traffic_source,payment_method,product_category,customer_age_days,previous_orders,avg_order_value_eur,...,shipping_distance_km,delivery_days_estimated,late_delivery_risk,address_mismatch,high_risk_ip,customer_support_contacts,review_score,is_returned,is_fraud,risk_label
0,ORD-2024-001936,2024-01-03,Belgium,Mobile,Paid Ads,Credit Card,Sports,381,3,28.66,...,105.7,5,0,0,0,0,4.4,0,0,Normal
1,ORD-2025-006495,2025-11-26,Netherlands,Desktop,Email,Debit Card,Garden,561,6,41.93,...,528.2,4,0,0,0,0,4.8,0,0,Normal
2,ORD-2023-001721,2023-11-07,Netherlands,Mobile,Organic Search,Debit Card,Garden,324,2,102.67,...,175.1,5,0,0,0,0,3.3,0,0,Normal
3,ORD-2024-009121,2024-05-28,Netherlands,Mobile,Organic Search,Klarna,Electronics,378,3,72.71,...,271.4,3,0,0,0,0,4.2,1,0,Return Risk
4,ORD-2025-000361,2025-01-31,Netherlands,Desktop,Direct,Bank Transfer,Home & Kitchen,447,5,52.26,...,285.3,3,0,1,0,0,5.0,0,0,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,ORD-2023-011965,2023-02-19,France,Mobile,Social Media,Credit Card,Garden,742,3,25.75,...,121.4,3,0,0,0,1,4.5,0,0,Normal
11996,ORD-2023-005192,2023-05-12,France,Mobile,Organic Search,Debit Card,Fashion,152,1,96.29,...,225.5,4,0,0,0,0,5.0,0,0,Normal
11997,ORD-2024-005391,2024-06-13,Germany,Mobile,Organic Search,Credit Card,Fashion,130,0,114.14,...,669.6,5,0,0,0,0,4.5,0,0,Normal
11998,ORD-2025-000861,2025-04-04,Poland,Desktop,Marketplace,PayPal,Fashion,203,1,21.60,...,229.4,5,0,0,0,0,4.4,0,0,Normal
11999,ORD-2024-007271,2024-05-23,Netherlands,Desktop,Organic Search,PayPal,Beauty,288,2,35.58,...,406.6,3,0,0,0,1,3.7,0,0,Normal

In [11]:
df['customer_age_days'].describe()

count    12000.000000
mean       352.789083
std        237.556088
min          5.000000
25%        177.000000
50%        299.000000
75%        475.000000
max       1832.000000
Name: customer_age_days, dtype: float64

In [12]:
df.max()

order_id                     ORD-2025-012000
order_date                        2025-12-31
country                               Turkey
device_type                           Tablet
traffic_source                  Social Media
payment_method                        PayPal
product_category                        Toys
customer_age_days                       1832
previous_orders                           13
avg_order_value_eur                   350.45
order_value_eur                       810.75
quantity                                   8
discount_rate                           0.75
shipping_distance_km                  2589.7
delivery_days_estimated                    9
late_delivery_risk                         1
address_mismatch                           1
high_risk_ip                               1
customer_support_contacts                  5
review_score                             5.0
is_returned                                1
is_fraud                                   1
risk_label                       Return Risk
dtype: object

In [13]:
df.mean

<bound method DataFrame.mean of               order_id  order_date      country device_type  traffic_source  \
0      ORD-2024-001936  2024-01-03      Belgium      Mobile        Paid Ads
1      ORD-2025-006495  2025-11-26  Netherlands     Desktop           Email
2      ORD-2023-001721  2023-11-07  Netherlands      Mobile  Organic Search
3      ORD-2024-009121  2024-05-28  Netherlands      Mobile  Organic Search
4      ORD-2025-000361  2025-01-31  Netherlands     Desktop          Direct
...                ...         ...          ...         ...             ...
11995  ORD-2023-011965  2023-02-19       France      Mobile    Social Media
11996  ORD-2023-005192  2023-05-12       France      Mobile  Organic Search
11997  ORD-2024-005391  2024-06-13      Germany      Mobile  Organic Search
11998  ORD-2025-000861  2025-04-04       Poland     Desktop     Marketplace
11999  ORD-2024-007271  2024-05-23  Netherlands     Desktop  Organic Search

      payment_method product_category  customer_age_days  previous_orders  \
0        Credit Card           Sports                381                3
1         Debit Card           Garden                561                6
2         Debit Card           Garden                324                2
3             Klarna      Electronics                378                3
4      Bank Transfer   Home & Kitchen                447                5
...              ...              ...                ...              ...
11995    Credit Card           Garden                742                3
11996     Debit Card          Fashion                152                1
11997    Credit Card          Fashion                130                0
11998         PayPal          Fashion                203                1
11999         PayPal           Beauty                288                2

       avg_order_value_eur  ...  shipping_distance_km  \
0                    28.66  ...                 105.7
1                    41.93  ...                 528.2
2                   102.67  ...                 175.1
3                    72.71  ...                 271.4
4                    52.26  ...                 285.3
...                    ...  ...                   ...
11995                25.75  ...                 121.4
11996                96.29  ...                 225.5
11997               114.14  ...                 669.6
11998                21.60  ...                 229.4
11999                35.58  ...                 406.6

       delivery_days_estimated  late_delivery_risk  address_mismatch  \
0                            5                   0                 0
1                            4                   0                 0
2                            5                   0                 0
3                            3                   0                 0
4                            3                   0                 1
...                        ...                 ...               ...
11995                        3                   0                 0
11996                        4                   0                 0
11997                        5                   0                 0
11998                        5                   0                 0
11999                        3                   0                 0

       high_risk_ip  customer_support_contacts  review_score  is_returned  \
0                 0                          0           4.4            0
1                 0                          0           4.8            0
2                 0                          0           3.3            0
3                 0                          0           4.2            1
4                 0                          0           5.0            0
...             ...                        ...           ...          ...
11995             0                          1           4.5            0
11996             0                          0           5.0            0
11997             0                          0           4.5            0
11998             0                          0           4.4            0
11999             0                          1           3.7            0

       is_fraud   risk_label
0             0       Normal
1             0       Normal
2             0       Normal
3             0  Return Risk
4             0       Normal
...         ...          ...
11995         0       Normal
11996         0       Normal
11997         0       Normal
11998         0       Normal
11999         0       Normal

[12000 rows x 23 columns]>

In [14]:
df['country'].unique()
df['device_type'].unique()

array(['Mobile', 'Desktop', 'Tablet'], dtype=object)

In [15]:
df['order_date']

0        2024-01-03
1        2025-11-26
2        2023-11-07
3        2024-05-28
4        2025-01-31
            ...
11995    2023-02-19
11996    2023-05-12
11997    2024-06-13
11998    2025-04-04
11999    2024-05-23
Name: order_date, Length: 12000, dtype: object

In [16]:
df['is_fraud'].unique()

array([0, 1])

In [17]:
df['customer_age_days'].describe()

count    12000.000000
mean       352.789083
std        237.556088
min          5.000000
25%        177.000000
50%        299.000000
75%        475.000000
max       1832.000000
Name: customer_age_days, dtype: float64

In [18]:
df['review_score'].unique()

array([4.4, 4.8, 3.3, 4.2, 5. , 3.7, 4.5, 4.6, 3.4, 3.9, 4.3, 3.5, 4.9,
       4. , 3.8, 4.7, 2.2, 4.1, 3.6, 3. , 3.2, 2.6, 2.4, 2.8, 2.7, 3.1,
       2.3, 1.9, 2.9, 1.7, 1.3, 2.1, 2.5, 2. , 1.8, 1.4])

In [19]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   order_id                   12000 non-null  object
 1   order_date                 12000 non-null  datetime64[ns]
 2   country                    12000 non-null  object
 3   device_type                12000 non-null  object
 4   traffic_source             12000 non-null  object
 5   payment_method             12000 non-null  object
 6   product_category           12000 non-null  object
 7   customer_age_days          12000 non-null  int64
 8   previous_orders            12000 non-null  int64
 9   avg_order_value_eur        12000 non-null  float64
 10  order_value_eur            12000 non-null  float64
 11  quantity                   12000 non-null  int64
 12  discount_rate              12000 non-null  float64
 13  shipping_distance_km       12000 non-null  float64
 14  delivery_days_estimated    12000 non-null  int64
 15  late_delivery_risk         12000 non-null  int64
 16  address_mismatch           12000 non-null  int64
 17  high_risk_ip               12000 non-null  int64
 18  customer_support_contacts  12000 non-null  int64
 19  review_score               12000 non-null  float64
 20  is_returned                12000 non-null  int64
 21  is_fraud                   12000 non-null  int64
 22  risk_label                 12000 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(10), object(7)
memory usage: 2.1+ MB

In [21]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['review_score'] = df['review_score'].round(1)

In [22]:
df.to_csv("E-Commerce Order Risk Classification Dataset", index=False)

In [23]:
df.to_excel("E-Commerce Order Risk Classification Dataset.xlsx", index=False)

In [24]:
df.head(5)

,order_id,order_date,country,device_type,traffic_source,payment_method,product_category,customer_age_days,previous_orders,avg_order_value_eur,...,shipping_distance_km,delivery_days_estimated,late_delivery_risk,address_mismatch,high_risk_ip,customer_support_contacts,review_score,is_returned,is_fraud,risk_label
0,ORD-2024-001936,2024-01-03,Belgium,Mobile,Paid Ads,Credit Card,Sports,381,3,28.66,...,105.7,5,0,0,0,0,4.4,0,0,Normal
1,ORD-2025-006495,2025-11-26,Netherlands,Desktop,Email,Debit Card,Garden,561,6,41.93,...,528.2,4,0,0,0,0,4.8,0,0,Normal
2,ORD-2023-001721,2023-11-07,Netherlands,Mobile,Organic Search,Debit Card,Garden,324,2,102.67,...,175.1,5,0,0,0,0,3.3,0,0,Normal
3,ORD-2024-009121,2024-05-28,Netherlands,Mobile,Organic Search,Klarna,Electronics,378,3,72.71,...,271.4,3,0,0,0,0,4.2,1,0,Return Risk
4,ORD-2025-000361,2025-01-31,Netherlands,Desktop,Direct,Bank Transfer,Home & Kitchen,447,5,52.26,...,285.3,3,0,1,0,0,5.0,0,0,Normal