In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/sumeakash/enhanced-superstore-sales-dataset/Global Superstore.csv

In [2]:
import pandas as pd
df=pd.read_csv("/kaggle/input/datasets/sumeakash/enhanced-superstore-sales-dataset/Global Superstore.csv")
df.head(1)

,Category,City,Country,Customer ID,Customer Name,Discount,Market,ji_lu-shu,Order Date,Order ID,...,Sales,Segment,Ship Date,Ship Mode,Shipping Cost,State,Sub-Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,00:00.0,CA-2011-130813,...,19,Consumer,00:00.0,Second Class,4.37,California,Paper,2011,North America,2

In [3]:
df.tail(1)

,Category,City,Country,Customer ID,Customer Name,Discount,Market,ji_lu-shu,Order Date,Order ID,...,Sales,Segment,Ship Date,Ship Mode,Shipping Cost,State,Sub-Category,Year,Market2,weeknum
51289,Office Supplies,Los Angeles,United States,FH-143654,Fred Hopkins,0.2,US,1,00:00.0,CA-2014-121398,...,154,Corporate,00:00.0,Standard Class,9.59,California,Binders,2014,North America,52

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        51290 non-null  object
 1   City            51290 non-null  object
 2   Country         51290 non-null  object
 3   Customer ID     51290 non-null  object
 4   Customer Name   51290 non-null  object
 5   Discount        51290 non-null  float64
 6   Market          51290 non-null  object
 7   ji_lu-shu       51290 non-null  int64
 8   Order Date      51290 non-null  object
 9   Order ID        51290 non-null  object
 10  Order Priority  51290 non-null  object
 11  Product ID      51290 non-null  object
 12  Product Name    51290 non-null  object
 13  Profit          51290 non-null  float64
 14  Quantity        51290 non-null  int64
 15  Region          51290 non-null  object
 16  Row ID          51290 non-null  int64
 17  Sales           51290 non-null  int64
 18  Segment         51290 non-null  object
 19  Ship Date       51290 non-null  object
 20  Ship Mode       51290 non-null  object
 21  Shipping Cost   51290 non-null  float64
 22  State           51290 non-null  object
 23  Sub-Category    51290 non-null  object
 24  Year            51290 non-null  int64
 25  Market2         51290 non-null  object
 26  weeknum         51290 non-null  int64
dtypes: float64(3), int64(6), object(18)
memory usage: 10.6+ MB

In [5]:
df.describe()

,Discount,ji_lu-shu,Profit,Quantity,Row ID,Sales,Shipping Cost,Year,weeknum
count,51290.000000,51290.0,51290.000000,51290.000000,51290.00000,51290.000000,51290.000000,51290.000000,51290.000000
mean,0.142908,1.0,28.610982,3.476545,25645.50000,246.498440,26.375818,2012.777208,31.287112
std,0.212280,0.0,174.340972,2.278766,14806.29199,487.567175,57.296810,1.098931,14.429795
min,0.000000,1.0,-6599.978000,1.000000,1.00000,0.000000,0.002000,2011.000000,1.000000
25%,0.000000,1.0,0.000000,2.000000,12823.25000,31.000000,2.610000,2012.000000,20.000000
50%,0.000000,1.0,9.240000,3.000000,25645.50000,85.000000,7.790000,2013.000000,33.000000
75%,0.200000,1.0,36.810000,5.000000,38467.75000,251.000000,24.450000,2014.000000,44.000000
max,0.850000,1.0,8399.976000,14.000000,51290.00000,22638.000000,933.570000,2014.000000,53.000000

In [6]:
df.max

<bound method DataFrame.max of               Category         City        Country Customer ID  \
0      Office Supplies  Los Angeles  United States   LS-172304
1      Office Supplies  Los Angeles  United States   MV-174854
2      Office Supplies  Los Angeles  United States   CS-121304
3      Office Supplies  Los Angeles  United States   CS-121304
4      Office Supplies  Los Angeles  United States   AP-109154
...                ...          ...            ...         ...
51285  Office Supplies  Los Angeles  United States   AM-103604
51286  Office Supplies  Los Angeles  United States   AM-103604
51287  Office Supplies  Los Angeles  United States   HR-147704
51288  Office Supplies  Los Angeles  United States   RM-196754
51289  Office Supplies  Los Angeles  United States   FH-143654

          Customer Name  Discount Market  ji_lu-shu Order Date  \
0      Lycoris Saunders       0.0     US          1    00:00.0
1         Mark Van Huff       0.0     US          1    00:00.0
2          Chad Sievert       0.0     US          1    00:00.0
3          Chad Sievert       0.0     US          1    00:00.0
4        Arthur Prichep       0.0     US          1    00:00.0
...                 ...       ...    ...        ...        ...
51285    Alice McCarthy       0.2     US          1    00:00.0
51286    Alice McCarthy       0.2     US          1    00:00.0
51287    Hallie Redmond       0.2     US          1    00:00.0
51288     Robert Marley       0.2     US          1    00:00.0
51289      Fred Hopkins       0.2     US          1    00:00.0

             Order ID  ... Sales      Segment Ship Date       Ship Mode  \
0      CA-2011-130813  ...    19     Consumer   00:00.0    Second Class
1      CA-2011-148614  ...    19     Consumer   00:00.0  Standard Class
2      CA-2011-118962  ...    21     Consumer   00:00.0  Standard Class
3      CA-2011-118962  ...   111     Consumer   00:00.0  Standard Class
4      CA-2011-146969  ...     6     Consumer   00:00.0  Standard Class
...               ...  ...   ...          ...       ...             ...
51285  CA-2014-109701  ...    69    Corporate   00:00.0        Same Day
51286  CA-2014-109701  ...     9    Corporate   00:00.0        Same Day
51287  CA-2014-106964  ...    12  Home Office   00:00.0     First Class
51288  CA-2014-145219  ...    90  Home Office   00:00.0     First Class
51289  CA-2014-121398  ...   154    Corporate   00:00.0  Standard Class

       Shipping Cost       State  Sub-Category  Year        Market2 weeknum
0               4.37  California         Paper  2011  North America       2
1               0.94  California         Paper  2011  North America       4
2               1.81  California         Paper  2011  North America      32
3               4.59  California         Paper  2011  North America      32
4               1.32  California         Paper  2011  North America      40
...              ...         ...           ...   ...            ...     ...
51285           5.15  California       Binders  2014  North America      49
51286           0.44  California       Binders  2014  North America      49
51287           0.31  California       Binders  2014  North America      51
51288          15.95  California       Binders  2014  North America      52
51289           9.59  California       Binders  2014  North America      52

[51290 rows x 27 columns]>

In [7]:
df.min

<bound method DataFrame.min of               Category         City        Country Customer ID  \
0      Office Supplies  Los Angeles  United States   LS-172304
1      Office Supplies  Los Angeles  United States   MV-174854
2      Office Supplies  Los Angeles  United States   CS-121304
3      Office Supplies  Los Angeles  United States   CS-121304
4      Office Supplies  Los Angeles  United States   AP-109154
...                ...          ...            ...         ...
51285  Office Supplies  Los Angeles  United States   AM-103604
51286  Office Supplies  Los Angeles  United States   AM-103604
51287  Office Supplies  Los Angeles  United States   HR-147704
51288  Office Supplies  Los Angeles  United States   RM-196754
51289  Office Supplies  Los Angeles  United States   FH-143654

          Customer Name  Discount Market  ji_lu-shu Order Date  \
0      Lycoris Saunders       0.0     US          1    00:00.0
1         Mark Van Huff       0.0     US          1    00:00.0
2          Chad Sievert       0.0     US          1    00:00.0
3          Chad Sievert       0.0     US          1    00:00.0
4        Arthur Prichep       0.0     US          1    00:00.0
...                 ...       ...    ...        ...        ...
51285    Alice McCarthy       0.2     US          1    00:00.0
51286    Alice McCarthy       0.2     US          1    00:00.0
51287    Hallie Redmond       0.2     US          1    00:00.0
51288     Robert Marley       0.2     US          1    00:00.0
51289      Fred Hopkins       0.2     US          1    00:00.0

             Order ID  ... Sales      Segment Ship Date       Ship Mode  \
0      CA-2011-130813  ...    19     Consumer   00:00.0    Second Class
1      CA-2011-148614  ...    19     Consumer   00:00.0  Standard Class
2      CA-2011-118962  ...    21     Consumer   00:00.0  Standard Class
3      CA-2011-118962  ...   111     Consumer   00:00.0  Standard Class
4      CA-2011-146969  ...     6     Consumer   00:00.0  Standard Class
...               ...  ...   ...          ...       ...             ...
51285  CA-2014-109701  ...    69    Corporate   00:00.0        Same Day
51286  CA-2014-109701  ...     9    Corporate   00:00.0        Same Day
51287  CA-2014-106964  ...    12  Home Office   00:00.0     First Class
51288  CA-2014-145219  ...    90  Home Office   00:00.0     First Class
51289  CA-2014-121398  ...   154    Corporate   00:00.0  Standard Class

       Shipping Cost       State  Sub-Category  Year        Market2 weeknum
0               4.37  California         Paper  2011  North America       2
1               0.94  California         Paper  2011  North America       4
2               1.81  California         Paper  2011  North America      32
3               4.59  California         Paper  2011  North America      32
4               1.32  California         Paper  2011  North America      40
...              ...         ...           ...   ...            ...     ...
51285           5.15  California       Binders  2014  North America      49
51286           0.44  California       Binders  2014  North America      49
51287           0.31  California       Binders  2014  North America      51
51288          15.95  California       Binders  2014  North America      52
51289           9.59  California       Binders  2014  North America      52

[51290 rows x 27 columns]>

In [8]:
df.shape

(51290, 27)

In [9]:
df.isnull().sum()

Category          0
City              0
Country           0
Customer ID       0
Customer Name     0
Discount          0
Market            0
ji_lu-shu         0
Order Date        0
Order ID          0
Order Priority    0
Product ID        0
Product Name      0
Profit            0
Quantity          0
Region            0
Row ID            0
Sales             0
Segment           0
Ship Date         0
Ship Mode         0
Shipping Cost     0
State             0
Sub-Category      0
Year              0
Market2           0
weeknum           0
dtype: int64

In [10]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
51285    False
51286    False
51287    False
51288    False
51289    False
Length: 51290, dtype: bool

In [11]:
df['Order Date'] = pd.to_datetime(df['Order Date'])

In [12]:
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        51290 non-null  object
 1   City            51290 non-null  object
 2   Country         51290 non-null  object
 3   Customer ID     51290 non-null  object
 4   Customer Name   51290 non-null  object
 5   Discount        51290 non-null  float64
 6   Market          51290 non-null  object
 7   ji_lu-shu       51290 non-null  int64
 8   Order Date      51290 non-null  datetime64[ns]
 9   Order ID        51290 non-null  object
 10  Order Priority  51290 non-null  object
 11  Product ID      51290 non-null  object
 12  Product Name    51290 non-null  object
 13  Profit          51290 non-null  float64
 14  Quantity        51290 non-null  int64
 15  Region          51290 non-null  object
 16  Row ID          51290 non-null  int64
 17  Sales           51290 non-null  int64
 18  Segment         51290 non-null  object
 19  Ship Date       51290 non-null  datetime64[ns]
 20  Ship Mode       51290 non-null  object
 21  Shipping Cost   51290 non-null  float64
 22  State           51290 non-null  object
 23  Sub-Category    51290 non-null  object
 24  Year            51290 non-null  int64
 25  Market2         51290 non-null  object
 26  weeknum         51290 non-null  int64
dtypes: datetime64[ns](2), float64(3), int64(6), object(16)
memory usage: 10.6+ MB

In [14]:
df['Category'].value_counts()

Category
Office Supplies    31273
Technology         10141
Furniture           9876
Name: count, dtype: int64

In [15]:
df['Category'].unique()

array(['Office Supplies', 'Technology', 'Furniture'], dtype=object)

In [16]:
df['City'].value_counts()

City
New York City    915
Los Angeles      747
Philadelphia     537
San Francisco    510
Santo Domingo    443
                ...
Chapel Hill        1
Goldsboro          1
Bartlett           1
Ormond Beach       1
Cuneo              1
Name: count, Length: 3636, dtype: int64

In [17]:
df['City'].unique()

array(['Los Angeles', 'San Francisco', 'San Diego', ..., 'Ontario',
       'Whittier', 'Redwood City'], shape=(3636,), dtype=object)

In [18]:
df['Country'].value_counts()

Country
United States    9994
Australia        2837
France           2827
Mexico           2644
Germany          2065
                 ...
Bahrain             2
Swaziland           2
Eritrea             2
South Sudan         2
Burundi             2
Name: count, Length: 147, dtype: int64

In [19]:
df['Country'].unique()

array(['United States', 'France', 'Germany', 'El Salvador', 'Guatemala',
       'Austria', 'Nicaragua', 'Belgium', 'Switzerland', 'Italy',
       'South Africa', 'India', 'Hong Kong',
       'Democratic Republic of the Congo', 'Cuba', 'United Kingdom',
       'Spain', 'Russia', 'China', 'Niger', 'Qatar', 'New Zealand',
       'Mexico', 'Malaysia', 'Poland', 'Madagascar', 'Iraq', 'Brazil',
       'Colombia', 'Saudi Arabia', 'Egypt', 'Iran', 'Ukraine', 'Japan',
       'Morocco', 'Cameroon', 'Chile', 'Ghana', 'Trinidad and Tobago',
       'Canada', 'Chad', 'Kenya', 'Bangladesh', 'Bulgaria', 'Djibouti',
       'Uruguay', 'Singapore', 'Czech Republic', 'Zambia', 'Bolivia',
       'Angola', 'Australia', 'Tanzania', 'Norway', 'Sierra Leone',
       'Hungary', 'Ecuador', 'Finland', 'Afghanistan', 'Uzbekistan',
       'Romania', 'Kyrgyzstan', 'Belarus', 'Mongolia', 'Georgia', 'Syria',
       'Croatia', 'Israel', 'Liberia', 'Guinea-Bissau', 'Somalia',
       'Senegal', 'Tunisia', 'Mali', 'Algeria', 'Benin', 'Ethiopia',
       'Libya', 'Mozambique', 'Guadeloupe', 'Jordan', 'Togo',
       "Cote d'Ivoire", 'Taiwan', 'Jamaica', 'Cambodia', 'Azerbaijan',
       'Lesotho', 'Bahrain', 'Montenegro', 'Moldova', 'Rwanda', 'Nepal',
       'Martinique', 'Estonia', 'Albania', 'Slovakia', 'Sudan', 'Guinea',
       'Republic of the Congo', 'Namibia', 'Sri Lanka',
       'Central African Republic', 'Eritrea', 'Lebanon',
       'Bosnia and Herzegovina', 'Barbados', 'Paraguay', 'Mauritania',
       'Swaziland', 'Gabon', 'Armenia', 'Slovenia', 'Macedonia',
       'Equatorial Guinea', 'South Sudan', 'Burundi', 'Turkey', 'Nigeria',
       'Turkmenistan', 'Kazakhstan', 'Lithuania', 'Yemen', 'Uganda',
       'Zimbabwe', 'United Arab Emirates', 'Sweden', 'Denmark', 'Ireland',
       'Portugal', 'Netherlands', 'South Korea', 'Pakistan',
       'Papua New Guinea', 'Thailand', 'Myanmar (Burma)', 'Vietnam',
       'Philippines', 'Indonesia', 'Dominican Republic', 'Haiti',
       'Panama', 'Honduras', 'Argentina', 'Peru', 'Venezuela',
       'Tajikistan'], dtype=object)

In [20]:
df['State'].value_counts()

State
California       2001
England          1499
New York         1128
Texas             985
Ile-de-France     981
                 ...
Pleven              1
Lima                1
Ibb                 1
Ardahan             1
Wyoming             1
Name: count, Length: 1094, dtype: int64

In [21]:
df['State'].unique()

array(['California', 'New York', 'Washington', ..., 'Tennessee', 'Oregon',
       'Wyoming'], shape=(1094,), dtype=object)

In [22]:
df['Market'].value_counts()

Market
APAC      11002
LATAM     10294
EU        10000
US         9994
EMEA       5029
Africa     4587
Canada      384
Name: count, dtype: int64

In [23]:
df['Market'].unique()

array(['US', 'EU', 'LATAM', 'Africa', 'APAC', 'EMEA', 'Canada'],
      dtype=object)

In [24]:
df['Segment'].value_counts()

Segment
Consumer       26518
Corporate      15429
Home Office     9343
Name: count, dtype: int64

In [25]:
df['Segment'].unique()

array(['Consumer', 'Home Office', 'Corporate'], dtype=object)

In [26]:
df['Ship Mode'].value_counts()

Ship Mode
Standard Class    30775
Second Class      10309
First Class        7505
Same Day           2701
Name: count, dtype: int64

In [27]:
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', 'Same Day', 'First Class'],
      dtype=object)

In [28]:
df['Sub-Category'].value_counts()

Sub-Category
Binders        6152
Storage        5059
Art            4883
Paper          3538
Chairs         3434
Phones         3357
Furnishings    3170
Accessories    3075
Labels         2606
Envelopes      2435
Supplies       2425
Fasteners      2420
Bookcases      2411
Copiers        2223
Appliances     1755
Machines       1486
Tables          861
Name: count, dtype: int64

In [29]:
df['Sub-Category'].unique()

array(['Paper', 'Art', 'Storage', 'Appliances', 'Supplies', 'Envelopes',
       'Fasteners', 'Labels', 'Binders', 'Accessories', 'Phones',
       'Copiers', 'Machines', 'Tables', 'Bookcases', 'Chairs',
       'Furnishings'], dtype=object)

In [30]:
df['Market2'].value_counts()

Market2
APAC             11002
North America    10378
LATAM            10294
EU               10000
EMEA              5029
Africa            4587
Name: count, dtype: int64

In [31]:
df['Market2'].unique()

array(['North America', 'EU', 'LATAM', 'Africa', 'APAC', 'EMEA'],
      dtype=object)

In [32]:
df.to_csv("Enhanced Superstore Sales Dataset.csv", index=False)

In [33]:
df.to_excel("Enhanced Superstore Sales Dataset.xlsx", index=False)