In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/newnguyn/steam-game-clean/SteamGames.csv
/kaggle/input/datasets/newnguyn/steam-game-clean/SteamGames_cleaned.csv

In [2]:
import numpy as np
import pandas as pd

df=pd.read_csv("/kaggle/input/datasets/newnguyn/steam-game-clean/SteamGames.csv")

df.head(1)

,Appid,Name,Type,ReleaseDate,Genres,Developers,Publishers,Description,price,Thumbnail,Tags,ReviewScore,PositiveReview,NegativeReview,OsRequirement,MemoryRequirement,CpuRequirement,Rank
0,3764200,Resident Evil Requiem,game,"Feb 26, 2026","Action,Adventure","CAPCOM Co., Ltd.","CAPCOM Co., Ltd.",Resident Evil Requiem Deluxe Edition Resident ...,69.99$,https://shared.akamai.steamstatic.com/store_it...,NaN,9,23715,793,NaN,NaN,NaN,1

In [3]:

dfnew=pd.read_csv("/kaggle/input/datasets/newnguyn/steam-game-clean/SteamGames_cleaned.csv")
dfnew.head(1)

,Appid,Name,Type,ReleaseDate,Genres,Developers,Publishers,Description,price,Thumbnail,...,ReviewScore,PositiveReview,NegativeReview,OsRequirement,MemoryRequirement,Rank,CPU_req,CPU_GHz,CPU_tier,tags
0,3764200,Resident Evil Requiem,game,2026-02-26,"Action,Adventure","CAPCOM Co., Ltd.","CAPCOM Co., Ltd.",Resident Evil Requiem Deluxe Edition Resident ...,69.99,https://shared.akamai.steamstatic.com/store_it...,...,9,23715,793,['no requirement'],0.0,1,0.0,0.0,0.0,"action, adventure"

In [4]:
df.describe()

,Appid,ReviewScore,PositiveReview,NegativeReview,Rank
count,2.993100e+04,29931.000000,2.993100e+04,29931.000000,29931.000000
mean,1.722531e+06,6.237145,1.443837e+03,193.180849,7585.978350
std,1.116414e+06,2.560245,1.368262e+04,2084.565186,4493.478798
min,1.000000e+01,0.000000,0.000000e+00,0.000000,1.000000
25%,7.511550e+05,6.000000,1.700000e+01,2.000000,3742.000000
50%,1.568970e+06,7.000000,5.900000e+01,9.000000,7483.000000
75%,2.587215e+06,8.000000,2.700000e+02,47.000000,11224.500000
max,4.460980e+06,9.000000,1.214897e+06,202393.000000,16719.000000

In [5]:
dfnew.describe()

,Appid,price,ReviewScore,PositiveReview,NegativeReview,MemoryRequirement,Rank,CPU_req,CPU_GHz,CPU_tier
count,2.990500e+04,29905.000000,29905.000000,2.990500e+04,29905.000000,2.986000e+04,29905.000000,29905.000000,29905.000000,29905.000000
mean,1.723483e+06,11.789654,6.238121,1.443402e+03,193.137235,4.062145e+03,14967.010968,0.871426,4.125316,0.865441
std,1.116176e+06,12.068100,2.559259,1.368771e+04,2085.337754,1.796947e+04,8639.392888,0.334733,210.347229,0.792313
min,1.000000e+01,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,1.000000,0.000000,0.000000,0.000000
25%,7.525800e+05,3.990000,6.000000,1.700000e+01,2.000000,1.024000e+03,7485.000000,1.000000,1.500000,0.000000
50%,1.569330e+06,8.990000,7.000000,5.900000e+01,9.000000,4.096000e+03,14965.000000,1.000000,2.300000,1.000000
75%,2.587590e+06,14.990000,8.000000,2.700000e+02,47.000000,6.144000e+03,22450.000000,1.000000,2.800000,1.000000
max,4.460980e+06,299.990000,9.000000,1.214897e+06,202393.000000,2.097152e+06,29931.000000,1.000000,21003.100000,4.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29931 entries, 0 to 29930
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Appid              29931 non-null  int64
 1   Name               29931 non-null  object
 2   Type               29931 non-null  object
 3   ReleaseDate        29917 non-null  object
 4   Genres             29518 non-null  object
 5   Developers         29905 non-null  object
 6   Publishers         28886 non-null  object
 7   Description        29879 non-null  object
 8   price              29931 non-null  object
 9   Thumbnail          29931 non-null  object
 10  Tags               28317 non-null  object
 11  ReviewScore        29931 non-null  int64
 12  PositiveReview     29931 non-null  int64
 13  NegativeReview     29931 non-null  int64
 14  OsRequirement      26994 non-null  object
 15  MemoryRequirement  25947 non-null  object
 16  CpuRequirement     26072 non-null  object
 17  Rank               29931 non-null  int64
dtypes: int64(5), object(13)
memory usage: 4.1+ MB

In [7]:
dfnew.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29905 entries, 0 to 29904
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Appid              29905 non-null  int64
 1   Name               29880 non-null  object
 2   Type               29905 non-null  object
 3   ReleaseDate        29905 non-null  object
 4   Genres             29499 non-null  object
 5   Developers         29671 non-null  object
 6   Publishers         29740 non-null  object
 7   Description        29905 non-null  object
 8   price              29905 non-null  float64
 9   Thumbnail          29905 non-null  object
 10  Tags               29676 non-null  object
 11  ReviewScore        29905 non-null  int64
 12  PositiveReview     29905 non-null  int64
 13  NegativeReview     29905 non-null  int64
 14  OsRequirement      29905 non-null  object
 15  MemoryRequirement  29860 non-null  float64
 16  Rank               29905 non-null  int64
 17  CPU_req            29905 non-null  float64
 18  CPU_GHz            29905 non-null  float64
 19  CPU_tier           29905 non-null  float64
 20  tags               29618 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 4.8+ MB

In [8]:
df.isnull().sum()

Appid                   0
Name                    0
Type                    0
ReleaseDate            14
Genres                413
Developers             26
Publishers           1045
Description            52
price                   0
Thumbnail               0
Tags                 1614
ReviewScore             0
PositiveReview          0
NegativeReview          0
OsRequirement        2937
MemoryRequirement    3984
CpuRequirement       3859
Rank                    0
dtype: int64

In [9]:
dfnew.isnull().sum()

Appid                  0
Name                  25
Type                   0
ReleaseDate            0
Genres               406
Developers           234
Publishers           165
Description            0
price                  0
Thumbnail              0
Tags                 229
ReviewScore            0
PositiveReview         0
NegativeReview         0
OsRequirement          0
MemoryRequirement     45
Rank                   0
CPU_req                0
CPU_GHz                0
CPU_tier               0
tags                 287
dtype: int64

In [10]:
df.dropna(inplace=True)

In [11]:
dfnew.dropna(inplace=True)

In [12]:
df.isnull().sum()

Appid                0
Name                 0
Type                 0
ReleaseDate          0
Genres               0
Developers           0
Publishers           0
Description          0
price                0
Thumbnail            0
Tags                 0
ReviewScore          0
PositiveReview       0
NegativeReview       0
OsRequirement        0
MemoryRequirement    0
CpuRequirement       0
Rank                 0
dtype: int64

In [13]:
dfnew.isnull().sum()

Appid                0
Name                 0
Type                 0
ReleaseDate          0
Genres               0
Developers           0
Publishers           0
Description          0
price                0
Thumbnail            0
Tags                 0
ReviewScore          0
PositiveReview       0
NegativeReview       0
OsRequirement        0
MemoryRequirement    0
Rank                 0
CPU_req              0
CPU_GHz              0
CPU_tier             0
tags                 0
dtype: int64

In [14]:
df.duplicated()

1        False
2        False
4        False
5        False
7        False
         ...
29925    False
29927    False
29928    False
29929    False
29930    False
Length: 24395, dtype: bool

In [15]:
dfnew.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
29900    False
29901    False
29902    False
29903    False
29904    False
Length: 29132, dtype: bool

In [16]:
df['ReleaseDate'] = pd.to_datetime(df['ReleaseDate'], format='mixed', errors='coerce')

In [17]:
dfnew['ReleaseDate'] = pd.to_datetime(df['ReleaseDate'], format='mixed', errors='coerce')

In [18]:
df['price'] = pd.to_numeric(df['price'], errors='coerce')

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24395 entries, 1 to 29930
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Appid              24395 non-null  int64
 1   Name               24395 non-null  object
 2   Type               24395 non-null  object
 3   ReleaseDate        24395 non-null  datetime64[ns]
 4   Genres             24395 non-null  object
 5   Developers         24395 non-null  object
 6   Publishers         24395 non-null  object
 7   Description        24395 non-null  object
 8   price              0 non-null      float64
 9   Thumbnail          24395 non-null  object
 10  Tags               24395 non-null  object
 11  ReviewScore        24395 non-null  int64
 12  PositiveReview     24395 non-null  int64
 13  NegativeReview     24395 non-null  int64
 14  OsRequirement      24395 non-null  object
 15  MemoryRequirement  24395 non-null  object
 16  CpuRequirement     24395 non-null  object
 17  Rank               24395 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(5), object(11)
memory usage: 4.0+ MB

In [20]:
dfnew.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29132 entries, 0 to 29904
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Appid              29132 non-null  int64
 1   Name               29132 non-null  object
 2   Type               29132 non-null  object
 3   ReleaseDate        23741 non-null  datetime64[ns]
 4   Genres             29132 non-null  object
 5   Developers         29132 non-null  object
 6   Publishers         29132 non-null  object
 7   Description        29132 non-null  object
 8   price              29132 non-null  float64
 9   Thumbnail          29132 non-null  object
 10  Tags               29132 non-null  object
 11  ReviewScore        29132 non-null  int64
 12  PositiveReview     29132 non-null  int64
 13  NegativeReview     29132 non-null  int64
 14  OsRequirement      29132 non-null  object
 15  MemoryRequirement  29132 non-null  float64
 16  Rank               29132 non-null  int64
 17  CPU_req            29132 non-null  float64
 18  CPU_GHz            29132 non-null  float64
 19  CPU_tier           29132 non-null  float64
 20  tags               29132 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(5), object(10)
memory usage: 4.9+ MB

In [21]:
df['Type'].unique()

array(['game', 'dlc', 'music', 'mod'], dtype=object)

In [22]:
df['Genres'].unique()

array(['Action,Free To Play', 'Action', 'Action,Adventure,Free To Play',
       ...,
       'Action,Indie,Massively Multiplayer,RPG,Simulation,Early Access',
       'Casual,Free To Play,Simulation,Sports',
       'Casual,Indie,Massively Multiplayer,Racing,Simulation,Sports,Early Access'],
      dtype=object)

In [23]:
df['Developers'].unique()

array(['Valve', 'Embark Studios', 'Respawn', ..., 'Veritable Joy Studios',
       'Kiralice Sha', 'Return To Adventure Mountain, LLC'], dtype=object)

In [24]:
df['Publishers'].unique()

array(['Valve', 'Embark Studios', 'Electronic Arts', ...,
       'Ticking Clock Games', 'Veritable Joy Studios ',
       'Return To Adventure Mountain, LLC'], dtype=object)

In [25]:
df['Tags'].unique()

array(['FPS,Shooter,Multiplayer,Competitive,Action,Team-Based,eSports,Tactical,First-Person,PvP,Online Co-Op,Co-op,Strategy,Military,War,Difficult,Trading,Realistic,Fast-Paced,Moddable',
       'Extraction Shooter,Multiplayer,PvP,PvE,Third-Person Shooter,Post-apocalyptic,Shooter,Online Co-Op,Survival,Sci-fi,Atmospheric,Third Person,Crafting,Inventory Management,Action,Open World,Combat,Futuristic,Character Customization,Realistic',
       'Free to Play,Multiplayer,Battle Royale,FPS,Shooter,First-Person,PvP,Action,Hero Shooter,Team-Based,Tactical,Sci-fi,Co-op,Loot,Survival,Character Customization,Funny,Cyberpunk,Lore-Rich,Cinematic',
       ...,
       'LGBTQ+,Female Protagonist,JRPG,Indie,Story Rich,Fantasy,RPG,Casual,Pixel Graphics,Exploration,Turn-Based Combat,2D,RPGMaker,Turn-Based,Cute,Party-Based RPG,Dungeon Crawler,Singleplayer,Adventure,Sexual Content',
       'Singleplayer,RPG,2D,Fantasy,Pixel Graphics,Story Rich,Free to Play,Combat',
       'Precision Platformer,Difficult,2D Platformer,Side Scroller,Platformer,Female Protagonist,2D,Action,Pixel Graphics,Sci-fi,Adventure,Retro,Singleplayer,Short,Minimalist'],
      dtype=object)

In [26]:
df['OsRequirement'].unique()

array(['Windows® 10', 'Windows 10 or later 64-bit (latest update)',
       '64-bit Windows 10', ..., 'Microsoft® Windows® 10 x64',
       'Windows® 7 / Windows Vista® / Windows® 8 / Windows® 10',
       'Windows 7 32 Bit or higher'], dtype=object)

In [27]:
df['Publishers'] = df['Publishers'].str.strip()
df['Developers'] = df['Developers'].str.strip()

In [28]:
dfnew['Developers'].unique()

array(['CAPCOM Co., Ltd.', 'Valve', 'Embark Studios', ..., 'Kiralice Sha',
       'LunaRolexLer', 'Return To Adventure Mountain, LLC'], dtype=object)

In [29]:
dfnew['Publishers'].unique()

array(['CAPCOM Co., Ltd.', 'Valve', 'Embark Studios', ...,
       'Veritable Joy Studios', 'LunaRolexLer',
       'Return To Adventure Mountain, LLC'], dtype=object)

In [30]:
df['Genres'] = df['Genres'].str.split(',')

In [31]:
dfnew['Genres'] = df['Genres'].str.split(',')

In [32]:
df = df.explode('Genres')

In [33]:
dfnew = dfnew.explode('Genres')

In [34]:
df['Type'].value_counts()

Type
game     56414
dlc      10499
music       59
mod         59
Name: count, dtype: int64

In [35]:
dfnew['Type'].value_counts()

Type
game     22350
dlc       6526
music      230
mod         26
Name: count, dtype: int64

In [36]:
df.max

<bound method DataFrame.max of          Appid                 Name  Type ReleaseDate        Genres  \
1          730     Counter-Strike 2  game  2012-08-21        Action
1          730     Counter-Strike 2  game  2012-08-21  Free To Play
2      1808500          ARC Raiders  game  2025-10-30        Action
4      1172470        Apex Legends™  game  2020-11-04        Action
4      1172470        Apex Legends™  game  2020-11-04     Adventure
...        ...                  ...   ...         ...           ...
29929  3956320             Inotia 4  game  2025-12-07           RPG
29929  3956320             Inotia 4  game  2025-12-07  Free To Play
29930   791180  1 Screen Platformer  game  2019-03-06        Action
29930   791180  1 Screen Platformer  game  2019-03-06     Adventure
29930   791180  1 Screen Platformer  game  2019-03-06         Indie

                              Developers                         Publishers  \
1                                  Valve                              Valve
1                                  Valve                              Valve
2                         Embark Studios                     Embark Studios
4                                Respawn                    Electronic Arts
4                                Respawn                    Electronic Arts
...                                  ...                                ...
29929                             Com2uS                             Com2uS
29929                             Com2uS                             Com2uS
29930  Return To Adventure Mountain, LLC  Return To Adventure Mountain, LLC
29930  Return To Adventure Mountain, LLC  Return To Adventure Mountain, LLC
29930  Return To Adventure Mountain, LLC  Return To Adventure Mountain, LLC

                                             Description  price  \
1      For over two decades, Counter-Strike has offer...    NaN
1      For over two decades, Counter-Strike has offer...    NaN
2      ARC Raiders Deluxe Edition ARC Raiders Deluxe ...    NaN
4      Apex Legends: Breach About the Game Conquer wi...    NaN
4      Apex Legends: Breach About the Game Conquer wi...    NaN
...                                                  ...    ...
29929  The grand adventure across the continent of In...    NaN
29929  The grand adventure across the continent of In...    NaN
29930  Get ready because the sequel is coming soon: T...    NaN
29930  Get ready because the sequel is coming soon: T...    NaN
29930  Get ready because the sequel is coming soon: T...    NaN

                                               Thumbnail  \
1      https://shared.akamai.steamstatic.com/store_it...
1      https://shared.akamai.steamstatic.com/store_it...
2      https://shared.akamai.steamstatic.com/store_it...
4      https://shared.akamai.steamstatic.com/store_it...
4      https://shared.akamai.steamstatic.com/store_it...
...                                                  ...
29929  https://shared.akamai.steamstatic.com/store_it...
29929  https://shared.akamai.steamstatic.com/store_it...
29930  https://shared.akamai.steamstatic.com/store_it...
29930  https://shared.akamai.steamstatic.com/store_it...
29930  https://shared.akamai.steamstatic.com/store_it...

                                                    Tags  ReviewScore  \
1      FPS,Shooter,Multiplayer,Competitive,Action,Tea...            8
1      FPS,Shooter,Multiplayer,Competitive,Action,Tea...            8
2      Extraction Shooter,Multiplayer,PvP,PvE,Third-P...            8
4      Free to Play,Multiplayer,Battle Royale,FPS,Sho...            6
4      Free to Play,Multiplayer,Battle Royale,FPS,Sho...            6
...                                                  ...          ...
29929  Singleplayer,RPG,2D,Fantasy,Pixel Graphics,Sto...            0
29929  Singleplayer,RPG,2D,Fantasy,Pixel Graphics,Sto...            0
29930  Precision Platformer,Difficult,2D Platformer,S...            8
29930  Precision Platformer,Difficult,2D Platformer,S...            8
29930  Precision Platformer,Difficult,2D Platformer,S...            8

       PositiveReview  NegativeReview  \
1             1214897          202393
1             1214897          202393
2              149531           23194
4                 820             216
4                 820             216
...               ...             ...
29929               0               0
29929               0               0
29930             147              22
29930             147              22
29930             147              22

                                    OsRequirement MemoryRequirement  \
1                                     Windows® 10          8 GB RAM
1                                     Windows® 10          8 GB RAM
2      Windows 10 or later 64-bit (latest update)         12 GB RAM
4                               64-bit Windows 10          6 GB RAM
4                               64-bit Windows 10          6 GB RAM
...                                           ...               ...
29929                          Windows 10 (64bit)          8 GB RAM
29929                          Windows 10 (64bit)          8 GB RAM
29930                          Windows 7 or Later          1 GB RAM
29930                          Windows 7 or Later          1 GB RAM
29930                          Windows 7 or Later          1 GB RAM

                                          CpuRequirement   Rank
1      4 hardware CPU threads - Intel® Core™ i5 750 o...      2
1      4 hardware CPU threads - Intel® Core™ i5 750 o...      2
2      Intel Core i5-6600K or AMD Ryzen R5 1600 proce...      3
4      AMD FX 4350 or Equivalent, Intel Core i3 6300 ...      5
4      AMD FX 4350 or Equivalent, Intel Core i3 6300 ...      5
...                                                  ...    ...
29929                        Ryzen 2200g / Intel i3 8100  16718
29929                        Ryzen 2200g / Intel i3 8100  16718
29930                                              2 GHz  16719
29930                                              2 GHz  16719
29930                                              2 GHz  16719

[67031 rows x 18 columns]>

In [37]:
df.min

<bound method DataFrame.min of          Appid                 Name  Type ReleaseDate        Genres  \
1          730     Counter-Strike 2  game  2012-08-21        Action
1          730     Counter-Strike 2  game  2012-08-21  Free To Play
2      1808500          ARC Raiders  game  2025-10-30        Action
4      1172470        Apex Legends™  game  2020-11-04        Action
4      1172470        Apex Legends™  game  2020-11-04     Adventure
...        ...                  ...   ...         ...           ...
29929  3956320             Inotia 4  game  2025-12-07           RPG
29929  3956320             Inotia 4  game  2025-12-07  Free To Play
29930   791180  1 Screen Platformer  game  2019-03-06        Action
29930   791180  1 Screen Platformer  game  2019-03-06     Adventure
29930   791180  1 Screen Platformer  game  2019-03-06         Indie

                              Developers                         Publishers  \
1                                  Valve                              Valve
1                                  Valve                              Valve
2                         Embark Studios                     Embark Studios
4                                Respawn                    Electronic Arts
4                                Respawn                    Electronic Arts
...                                  ...                                ...
29929                             Com2uS                             Com2uS
29929                             Com2uS                             Com2uS
29930  Return To Adventure Mountain, LLC  Return To Adventure Mountain, LLC
29930  Return To Adventure Mountain, LLC  Return To Adventure Mountain, LLC
29930  Return To Adventure Mountain, LLC  Return To Adventure Mountain, LLC

                                             Description  price  \
1      For over two decades, Counter-Strike has offer...    NaN
1      For over two decades, Counter-Strike has offer...    NaN
2      ARC Raiders Deluxe Edition ARC Raiders Deluxe ...    NaN
4      Apex Legends: Breach About the Game Conquer wi...    NaN
4      Apex Legends: Breach About the Game Conquer wi...    NaN
...                                                  ...    ...
29929  The grand adventure across the continent of In...    NaN
29929  The grand adventure across the continent of In...    NaN
29930  Get ready because the sequel is coming soon: T...    NaN
29930  Get ready because the sequel is coming soon: T...    NaN
29930  Get ready because the sequel is coming soon: T...    NaN

                                               Thumbnail  \
1      https://shared.akamai.steamstatic.com/store_it...
1      https://shared.akamai.steamstatic.com/store_it...
2      https://shared.akamai.steamstatic.com/store_it...
4      https://shared.akamai.steamstatic.com/store_it...
4      https://shared.akamai.steamstatic.com/store_it...
...                                                  ...
29929  https://shared.akamai.steamstatic.com/store_it...
29929  https://shared.akamai.steamstatic.com/store_it...
29930  https://shared.akamai.steamstatic.com/store_it...
29930  https://shared.akamai.steamstatic.com/store_it...
29930  https://shared.akamai.steamstatic.com/store_it...

                                                    Tags  ReviewScore  \
1      FPS,Shooter,Multiplayer,Competitive,Action,Tea...            8
1      FPS,Shooter,Multiplayer,Competitive,Action,Tea...            8
2      Extraction Shooter,Multiplayer,PvP,PvE,Third-P...            8
4      Free to Play,Multiplayer,Battle Royale,FPS,Sho...            6
4      Free to Play,Multiplayer,Battle Royale,FPS,Sho...            6
...                                                  ...          ...
29929  Singleplayer,RPG,2D,Fantasy,Pixel Graphics,Sto...            0
29929  Singleplayer,RPG,2D,Fantasy,Pixel Graphics,Sto...            0
29930  Precision Platformer,Difficult,2D Platformer,S...            8
29930  Precision Platformer,Difficult,2D Platformer,S...            8
29930  Precision Platformer,Difficult,2D Platformer,S...            8

       PositiveReview  NegativeReview  \
1             1214897          202393
1             1214897          202393
2              149531           23194
4                 820             216
4                 820             216
...               ...             ...
29929               0               0
29929               0               0
29930             147              22
29930             147              22
29930             147              22

                                    OsRequirement MemoryRequirement  \
1                                     Windows® 10          8 GB RAM
1                                     Windows® 10          8 GB RAM
2      Windows 10 or later 64-bit (latest update)         12 GB RAM
4                               64-bit Windows 10          6 GB RAM
4                               64-bit Windows 10          6 GB RAM
...                                           ...               ...
29929                          Windows 10 (64bit)          8 GB RAM
29929                          Windows 10 (64bit)          8 GB RAM
29930                          Windows 7 or Later          1 GB RAM
29930                          Windows 7 or Later          1 GB RAM
29930                          Windows 7 or Later          1 GB RAM

                                          CpuRequirement   Rank
1      4 hardware CPU threads - Intel® Core™ i5 750 o...      2
1      4 hardware CPU threads - Intel® Core™ i5 750 o...      2
2      Intel Core i5-6600K or AMD Ryzen R5 1600 proce...      3
4      AMD FX 4350 or Equivalent, Intel Core i3 6300 ...      5
4      AMD FX 4350 or Equivalent, Intel Core i3 6300 ...      5
...                                                  ...    ...
29929                        Ryzen 2200g / Intel i3 8100  16718
29929                        Ryzen 2200g / Intel i3 8100  16718
29930                                              2 GHz  16719
29930                                              2 GHz  16719
29930                                              2 GHz  16719

[67031 rows x 18 columns]>

In [38]:
dfnew.max()

Appid                                                          4460980
Name                                                              €100
Type                                                             music
ReleaseDate                                        2026-05-29 00:00:00
Genres                                                            None
Developers                                                           ∇
Publishers                                                           ∇
Description          ⏹ Summary It has been several hundred years si...
price                                                           299.99
Thumbnail                                                           {}
Tags                 Zombies,VR,Violent,Gore,Action,Indie,RPG,Shoot...
ReviewScore                                                          9
PositiveReview                                                 1214897
NegativeReview                                                  202393
OsRequirement                                              ['windows']
MemoryRequirement                                            2097152.0
Rank                                                             29931
CPU_req                                                            1.0
CPU_GHz                                                        21003.1
CPU_tier                                                           4.0
tags                                                                vr
dtype: object

In [39]:
dfnew.min

<bound method DataFrame.min of          Appid                                    Name  Type ReleaseDate  \
0      3764200                   Resident Evil Requiem  game         NaT
1          730                        Counter-Strike 2  game  2012-08-21
2      1808500                             ARC Raiders  game  2025-10-30
3       359550          Tom Clancy's Rainbow Six Siege  game         NaT
4      1172470                           Apex Legends™  game  2020-11-04
...        ...                                     ...   ...         ...
29900   843170                                ILLUSION  game         NaT
29901  1308250                      Knight Bewitched 2  game  2018-12-07
29902  1729610  Redmatch 2 - Fashionable Attire Bundle   dlc  2021-11-09
29903  3956320                                Inotia 4  game  2024-03-23
29904   791180                     1 Screen Platformer  game         NaT

      Genres                         Developers  \
0        NaN                   CAPCOM Co., Ltd.
1        NaN                              Valve
2        NaN                     Embark Studios
3        NaN                   Ubisoft Montreal
4        NaN                            Respawn
...      ...                                ...
29900    NaN                       LunaRolexLer
29901    NaN                       Joshua Keith
29902    NaN                     Rugbug Redfern
29903    NaN                             Com2uS
29904    NaN  Return To Adventure Mountain, LLC

                              Publishers  \
0                       CAPCOM Co., Ltd.
1                                  Valve
2                         Embark Studios
3                                Ubisoft
4                        Electronic Arts
...                                  ...
29900                       LunaRolexLer
29901                       Joshua Keith
29902                     Rugbug Redfern
29903                             Com2uS
29904  Return To Adventure Mountain, LLC

                                             Description  price  \
0      Resident Evil Requiem Deluxe Edition Resident ...  69.99
1      For over two decades, Counter-Strike has offer...   0.00
2      ARC Raiders Deluxe Edition ARC Raiders Deluxe ...  39.99
3      Season 11 Year 1 Overview Year 11 Roadmap Free...   0.00
4      Apex Legends: Breach About the Game Conquer wi...   0.00
...                                                  ...    ...
29900  Guilt Is The Feeling That Makes You Human. Thi...   1.99
29901  Knight Bewitched 2 is a jRPG featuring the sto...   4.99
29902  Bundle Content: Top Hat (Hat) Halo (Hat) Prope...   4.99
29903  The grand adventure across the continent of In...   0.00
29904  Get ready because the sequel is coming soon: T...   2.99

                                               Thumbnail  ... ReviewScore  \
0      https://shared.akamai.steamstatic.com/store_it...  ...           9
1      https://shared.akamai.steamstatic.com/store_it...  ...           8
2      https://shared.akamai.steamstatic.com/store_it...  ...           8
3      https://shared.akamai.steamstatic.com/store_it...  ...           8
4      https://shared.akamai.steamstatic.com/store_it...  ...           6
...                                                  ...  ...         ...
29900  https://shared.akamai.steamstatic.com/store_it...  ...           7
29901  https://shared.akamai.steamstatic.com/store_it...  ...           7
29902  https://shared.akamai.steamstatic.com/store_it...  ...           0
29903  https://shared.akamai.steamstatic.com/store_it...  ...           0
29904  https://shared.akamai.steamstatic.com/store_it...  ...           8

       PositiveReview  NegativeReview       OsRequirement MemoryRequirement  \
0               23715             793  ['no requirement']               0.0
1             1214897          202393         ['windows']            8192.0
2              149531           23194         ['windows']           12288.0
3              522886          106839  ['no requirement']               0.0
4                 820             216         ['windows']            6144.0
...               ...             ...                 ...               ...
29900              39               2         ['windows']             100.0
29901              24               0         ['windows']            2048.0
29902               7               1         ['windows']            4096.0
29903               0               0         ['windows']            8192.0
29904             147              22         ['windows']            1024.0

        Rank  CPU_req  CPU_GHz  CPU_tier  \
0          1      0.0      0.0       0.0
1          2      1.0      3.0       2.0
2          3      1.0      3.0       2.0
3          4      0.0      0.0       0.0
4          5      1.0      2.3       1.0
...      ...      ...      ...       ...
29900  29927      0.0      0.0       0.0
29901  29928      1.0      2.2       0.0
29902  29929      1.0      2.6       1.0
29903  29930      1.0      2.3       1.0
29904  29931      1.0      2.0       0.0

                                                    tags
0                                      action, adventure
1      action, strategy, multiplayer, first-person, s...
2      action, atmospheric, multiplayer, shooter, sci...
3                                   action, free-to-play
4      action, multiplayer, first-person, funny, shoo...
...                                                  ...
29900  singleplayer, indie, action, adventure, casual...
29901  singleplayer, indie, adventure, casual, 2d, rp...
29902                        indie, action, free-to-play
29903  singleplayer, 2d, rpg, story rich, pixel graph...
29904  singleplayer, action, adventure, 2d, pixel gra...

[29132 rows x 21 columns]>

In [40]:
df.shape

(67031, 18)

In [41]:
dfnew.shape

(29132, 21)

In [42]:
df.to_csv("Steam_Game_MetaData.csv", index=False)

In [43]:
df.to_excel("Steam_Game_MetaData.xlsx", index=False)

In [44]:
dfnew.to_csv("Steam_Game_cleaned.csv", index=False)

In [45]:
dfnew.to_excel("Steam_Game_cleaned.xlsx", index=False)